name: collections_repository
description: A repository that handles collection related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collections_api:
    path: ../collections_api
  todos_api:
    path: ../todos_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
